[paths]
logs_dir = 'logs'
reports_dir = 'reports'
levels_dir = 'levels'
assets_dir = 'assets'

[logging]
console_level = 'INFO'
file_level = 'DEBUG'
file_name = 'drunner.log'

[game]
window_width = 960
window_heigth = 540
fps = 60
title = 'Dungeon Runner'